### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by Sleeeeeeeeeep** [DuckySoLucky/Vape-V4#1]
why it have 50+ alerts of antivirus in the .exes in the .zip
![32okokrweerof](https://user-images.githubusercontent.com/76562701/185763515-736475c3-b4e2-4bd2-996b-b1b7526b3a14.PNG)
![ewwjregoif](https://user-images.githubusercontent.com/76562701/185763545-669cd479-7916-45c8-ad65-790e331b0c4e.PNG)

**Comment by DuckySoLucky** [comment]
As I told in README.md I do not own any of files except server. I and multiple ppl have used it and it works, You can run it in VM to make sure if u do not believe me. Have a nice day.

**Comment by Sleeeeeeeeeep** [comment]
LOOOOOOL u trying to rat newgens thats why u changed the title

**Comment by DuckySoLucky** [comment]
🤡

**Comment by Sleeeeeeeeeep** [comment]
LMFAO u dumbass or smt it haves 2 .exes in the code and the program installs it, the vape.exe and kangaroospatcher.exe code is rat

**Comment by DuckySoLucky** [comment]
Those files are not mine, download official kangaroo's crack and compare those two files using hex editor. You will see those files are same 🤡 
Try on VM as I told u
