### ISSUE TITLE
Getting python errors.

### ISSUE THREAD

**Issue by Liam5750** [DuckySoLucky/Vape-V4#12]
I ran the requirements thing and all that was successful. When I try to run server.py I do 'python server.py' while cd'd inside of the folder.
The issue is that running server.py gives me these errors:
![byhi235rghui9234r5gbyh8235ghui35gbhui3rgbhui](https://user-images.githubusercontent.com/74884194/209711887-49eac607-1dff-41c9-8880-24471db45e9b.PNG)

**Comment by Liam5750** [comment]
Now those errors are gone but I am getting:
![image](https://user-images.githubusercontent.com/74884194/209712294-421518f7-0ad0-479b-bb09-3b995403f28e.png)

**Comment by Liam5750** [comment]
It's working nvm

**Comment by OptfineTL** [comment]
how did u fix it?

**Comment by DuckySoLucky** [comment]
> how did u fix it?

Read README.md
