### ISSUE TITLE
Just blank cmd

### ISSUE THREAD

**Issue by Liam5750** [DuckySoLucky/Vape-V4#13]
So the server thing runs fine. But when I drop vapev4.exe over kangaroopatcher.exe and press "yes" it just shows a blank cmd attached to the current folder that vapev4.exe is in.

**Comment by Liam5750** [comment]
Ok so I fixed that but now vape fails on 2/11 or something and in the Console it says "TLS handshake timed out" twice.

**Comment by SturmEnte007** [comment]
Fun fact: that data is flagged by 40 out of 70 antiviruses, should be more careful what you are downloading
