### ISSUE TITLE
Connection server problem

### ISSUE THREAD

**Issue by jawharkun** [DuckySoLucky/Vape-V4#2]
I want to solve this 

![Untitled](https://user-images.githubusercontent.com/82400853/186910740-e5c1a90e-c284-48f0-90d4-4ed395406f2b.png)

**Comment by DuckySoLucky** [comment]
Do you have web server running?
Contact me on Discord DuckySoLucky#5181 (for faster responses)

**Comment by DuckySoLucky** [comment]
Solved

Python version was incorrect (3.9.0 is required)
