### ISSUE TITLE
viruses detected

### ISSUE THREAD

**Issue by lemonsnotin** [DuckySoLucky/Vape-V4#23]
why does virustotal detect a trojan virus?

**Comment by DuckySoLucky** [comment]
False triggered, open in VM and you're gonna see it's legit..

**Comment by lemonsnotin** [comment]
virustotal is the best virus detector though

**Comment by lemonsnotin** [comment]
has like over 40 antiviruses

**Comment by lemonsnotin** [comment]
...

**Comment by DuckySoLucky** [comment]
Cool? If it were a virus GitHub would have banned this repo and my account ages ago 🤡, Test it on VM so even if it's "virus" how u say nothing is gonna happen to ur

**Comment by DuckySoLucky** [comment]
> ...

Some people have a life if u didn't know

**Comment by DuckySoLucky** [comment]
> virustotal is the best virus detector though

And has crap ton of false flags

**Comment by DuckySoLucky** [comment]
> > virustotal is the best virus detector though
> 
> And has crap ton of false flags

Example
https://user-images.githubusercontent.com/75372052/219716598-58e0ff4f-5ed5-4ad8-9f98-a47ac95d5060.mp4

**Comment by lemonsnotin** [comment]
> Cool? If it were a virus GitHub would have banned this repo and my account ages ago 🤡, Test it on VM so even if it's "virus" how u say nothing is gonna happen to ur

then how are there so many viruses on github?

**Comment by DuckySoLucky** [comment]
> > Cool? If it were a virus GitHub would have banned this repo and my account ages ago 🤡, Test it on VM so even if it's "virus" how u say nothing is gonna happen to ur
> 
> then how are there so many viruses on github?

Send me link of one virus on GitHub lmao

**Comment by lemonsnotin** [comment]
you telling me this aint a virus? https://github.com/AmalNay/Vape-V4

https://www.virustotal.com/gui/file/00310dcf38e02d26825864a4e969ba7be64ffe87c840f9708265d5e51c00bd20

so many flags no way they all false

**Comment by DuckySoLucky** [comment]
> you telling me this aint a virus? https://github.com/AmalNay/Vape-V4
> 
> https://www.virustotal.com/gui/file/00310dcf38e02d26825864a4e969ba7be64ffe87c840f9708265d5e51c00bd20
> 
> so many flags no way they all false

How is github suppose to detect virus in .rar file with password 🤡, if you're downloading any file with password online it's virus lmao

**Comment by DuckySoLucky** [comment]
If u think it's virus cool don't use it? Test it on VM you're gonna see it's legit... Also stars & forks can tell u that it's real..
If U don't like it don't use it, problem solved kiddo
