### ISSUE TITLE
Last version ?

### ISSUE THREAD

**Issue by trolldu47** [DuckySoLucky/Vape-V4#25]
Hello, I downloaded vape except that I realized that I do not have the same interface as the people who buy it as if I did not have the last update is it possible to put the latest update? Thanks in advance.

**Comment by DuckySoLucky** [comment]
Hello,

I understand that the current version of our software is outdated, and I appreciate your efforts to bring this to our attention. While we do have a more recent version, it is not currently available to the public as it requires a significant amount of time and resources to make it. There are no plans of making it publicly any time soon.

In the meantime, we encourage you to explore the concept behind the current version and learn how to implement similar solutions yourself. Thank you for your understanding and patience as we work towards providing a better experience for all of our users.

Best regards,
DuckySoLucky

**Comment by trolldu47** [comment]
Okay thank you no problam
