### ISSUE TITLE
skull

### ISSUE THREAD

**Issue by LePeeManPog** [DuckySoLucky/Vape-V4#26]
[errorfromserver.py.txt](https://github.com/DuckySoLucky/Vape-V4/files/10923411/errorfromserver.py.txt)
skull 2
![image](https://user-images.githubusercontent.com/79366404/223790502-943c61d4-cc95-46b6-bb5e-b63ed4290ab9.png)

**Comment by DuckySoLucky** [comment]
Contact me over discord `DuckySoLucky#5181`

**Comment by LePeeManPog** [comment]
done
