### ISSUE TITLE
On my computer, the server starts up with errors.

### ISSUE THREAD

**Issue by NitroDis0Free0** [DuckySoLucky/Vape-V4#29]
![image](https://user-images.githubusercontent.com/128484926/226628222-7da954cf-0178-4ded-8358-98d580cf840c.png)

**Comment by DuckySoLucky** [comment]
You do not have correct python version installed, you need 3.9.0. Not higher or lower

**Comment by NitroDis0Free0** [comment]
Thanks for the quick response. I will reinstall and report back.

**Comment by DuckySoLucky** [comment]
> No errors during startup. Thank you

Glad to help, lmk if there are any issues
