### ISSUE TITLE
I get the error that a dll is missing how do i fix?

### ISSUE THREAD

**Issue by Riley123132** [DuckySoLucky/Vape-V4#33]
![image](https://user-images.githubusercontent.com/129579878/229270268-31ea7575-ba6e-4c1a-886e-9bc6b7bef77e.png)

![image](https://user-images.githubusercontent.com/129579878/229270531-aef128f2-2f1f-4069-9e69-ae1c1687c63e.png)

**Comment by Riley123132** [comment]
plus why does microsoft Devender keep deleting it

**Comment by Riley123132** [comment]
Update I Found the error reason however every time i open the server it closes even with the right python download

**Comment by DuckySoLucky** [comment]
Contact me on Discord, `DuckySoLucky#5181`
