### ISSUE TITLE
websocket timed out

### ISSUE THREAD

**Issue by Lali346** [DuckySoLucky/Vape-V4#34]
![image](https://user-images.githubusercontent.com/88011060/229325844-9ebd44fa-8506-4901-95b9-5871e67c5e95.png)

**Comment by Lali346** [comment]
![image](https://user-images.githubusercontent.com/88011060/229326439-b1e5e175-bcc8-45a2-9314-bc4e1059a686.png)

**Comment by DuckySoLucky** [comment]
Heya, contact me on the discord `DuckySoLucky#5181`
