### ISSUE TITLE
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by Unkn0wnXD0** [DuckySoLucky/Vape-V4#36]
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   Cracked by DuckySoLucky#5181     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

1.7.10 » Connected
1.8.9 » Connected
1.12.2 » Connected

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃    localhost:8765     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛

Startup Complete

                                      NOTE

                 You can only use forge client with this server
Also you must not have any Sk1er mods (For example: Patcher) otherwise you're gonna crash
            You can't use Lunar, Badlion or any other custom client

Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...65066, 0, 0))>) at C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...65066, 0, 0))>) at C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840>
Traceback (most recent call last):
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 847, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'
PS C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1> 
PS C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1>
PS C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1> 
PS C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1>
PS C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1>
PS C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1>  c:; cd 'c:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1'; & 'C:\Users\msopy\AppData\Local\Programs\Python\Python311\python.exe' 'c:\Users\msopy\.vscode\extensions\ms-python.python-2023.6.0\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '65077' '--' 'C:\Users\msopy\Downloads\Vape-V4-1.1\Vape-V4-1.1\server.py' 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   Cracked by DuckySoLucky#5181     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

1.7.10 » Connected
1.8.9 » Connected
1.12.2 » Connected

┏━━━━━━━━━━━━━━━━━━━━━━━┓
┃    localhost:8765     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛

Startup Complete

                                      NOTE

                 You can only use forge client with this server
Also you must not have any Sk1er mods (For example: Patcher) otherwise you're gonna crash
            You can't use Lunar, Badlion or any other custom client

Exception in callback BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...65088, 0, 0))>) at C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840
handle: <Handle BaseProactorEventLoop._start_serving.<locals>.loop(<_OverlappedF...65088, 0, 0))>) at C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py:840>
Traceback (most recent call last):
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 847, in loop
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\server.py", line 103, in __init__
    super().__init__(**kwargs)
  File "C:\Users\msopy\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\protocol.py", line 235, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by DuckySoLucky** [comment]
You do not have correct python version installed.

Contact me on Discord `DuckySoLucky#5181` if you need more help
