### ISSUE TITLE
support for labymod

### ISSUE THREAD

**Issue by seraph-gh** [DuckySoLucky/Vape-V4#37]
**how would i go about making the client inject to other clients (labymod 1.8.9 specifically, any advice on how I should go about it?**
-
![image](https://user-images.githubusercontent.com/95204808/232227501-a791d852-bfee-4dd8-9808-b0ae1663aca1.png)
![image](https://user-images.githubusercontent.com/95204808/232227509-44e0674f-9c2b-4727-b492-de694e43e7f6.png)

**Comment by DuckySoLucky** [comment]
> ## **how would i go about making the client inject to other clients (labymod 1.8.9 specifically, any advice on how I should go about it?**
> ![image](https://user-images.githubusercontent.com/95204808/232227501-a791d852-bfee-4dd8-9808-b0ae1663aca1.png) ![image](https://user-images.githubusercontent.com/95204808/232227509-44e0674f-9c2b-4727-b492-de694e43e7f6.png)

Uhh, It works for me? Are you using custom laby mod instance or forge with laby as mod?
It works fine for me as mob for forge

**Comment by seraph-gh** [comment]
> Uhh, It works for me? Are you using custom laby mod instance or forge with laby as mod? It works fine for me as mod for forge
oh right, you can download labymod as a forge mod, yes I'm using a custom instance so the client wouldn't inject. I'll try to download labymod with forge. thanks!
