### ISSUE TITLE
VAPE V4.10 Doesn't work with Lunar Client v2.15.1

### ISSUE THREAD

**Issue by PlayMcBKuwu** [DuckySoLucky/Vape-V4#54]
I tried to start "vape.bat" in normal and administrator mode,
and it started a black console,few seconds it gone and Lunar Client doesn't apply changes(RShift doesn't work)

**Comment by i-Igor-i** [comment]
Interest fact. This repository contains backdoor:)

**Comment by PlayMcBKuwu** [comment]
> 兴趣事实。此存储库包含后门：）

SO MY PC WILL DIE???

**Comment by DuckySoLucky** [comment]
Contact me on Discord `DuckySoLucky#5181`
