### ISSUE TITLE
Do u know if it's safe or not now?

### ISSUE THREAD

**Issue by MopigamesYT** [DuckySoLucky/Vape-V4#6]
It has been quite a long time since you uploaded the crack, do you know if it is safe to run kangaroo's crack now? I am wondering if I should buy vape but I wanna try it before i pay for it...

**Comment by DuckySoLucky** [comment]
Yeah it's safe, Kangaroo doesn't control anything anymore. You host the server so there's no connection between You and kangaroo anymore

**Comment by MopigamesYT** [comment]
okay, and is this crack an outdated version? because it doesnt really looks like the ones i see in the showcase and everything...

**Comment by DuckySoLucky** [comment]
> okay, and is this crack an outdated version? because it doesnt really looks like the ones i see in the showcase and everything...

This is latest legit one, other ones are fake and have a virus

**Comment by NajmAjmal** [comment]
This one is also a virus DO NOT USE & UNINSTALL ASAP.

I ran this program through [VirusTotal](https://www.virustotal.com/gui/file/bef628b23396d36849beac1bf633859d02f82ae9dc877281862b7e9e85148ecd) and it is flagged as Malicious by over 50 antiviruses
