### ISSUE TITLE
vape doesn't work (and lite and v4)

### ISSUE THREAD

**Issue by hxur** [DuckySoLucky/Vape-V4#7]
hey (x_hur#2143 (aka the retarded guy)) so i already dm'd you but vape still doesn't work. i tried with 3.9 - doesnt work. i deleted python with an app which deletes it even from registry - no. server.py? - no.
please help me. i always get the same error (on forge obv)
![image](https://user-images.githubusercontent.com/117398024/199828371-c13ca3e7-adec-461d-a595-f90dc1da44f8.png)
ss - same for v4 and lite. please help me i beg you i dont want to spend 40 fucking dollars. ty . <3

**Comment by Enderman117** [comment]
Hi, Hxur I used vape v4 before for minecraft
Could you try to use a VPN?
Best,
Thanks,
Sanroblox.

**Comment by hxur** [comment]
> Hi, Hxur I used vape v4 before for minecraft
> Could you try to use a VPN?
> Best,
> Thanks,
> Sanroblox.

alright will try

**Comment by DuckySoLucky** [comment]
#3
