### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by developerman9876** [DuckySoLucky/Vape-V4#9]
yea uhh i didnt know what to expect, its pretty old its kinda like a vape 2 idk gui

![image](https://user-images.githubusercontent.com/117606597/200206700-1295a87f-a06f-4d52-99d3-e5bd930099b4.png)

**Comment by DuckySoLucky** [comment]
Hello, yeah this is an outdated version. The latest version is not cracked yet sorry ;-;
